### ISSUE TITLE
H5Tset_size(): size must be positive

### ISSUE THREAD

**Issue by LDAmorim** [openPMD/openPMD-api#1021]
Hi,

I have been using `openpmd-api` (much appreciated tool!), but, in a recent installation, my code got an error message connected to it (well `HDF5`) and I tested using your example file and found that same error.
Since I am not able to understand how to solve it and I haven't found similar topics in other issues/PRs (here, or in `spack` or in `HDF5`'s repos), I decided to open this issue.

**Performed steps**
Installed `spack` with the commands below (directly copied from `history` command with added comments):

```commandline
(...)
1909  spack install gcc
 1910  spack compiler find
# Forgot to load it first ...
 1911  spack load gcc
 1912  spack compiler find
 1913  gcc --version
# Output was 11.1.0
 1914  spack install cmake
 1915  spack load cmake
 1916  spack install mpich
 1917  spack load mpich
 1918  vi /home/lidipiamorim/work/opt/spack/etc/spack/defaults/packages.yaml
# Changed line to mpi: [mpich, openmpi] so that spack compiles and runs with mpich instead of openmpi by default
 1919  spack install openpmd-api@dev
# Previous line gave an error (since I've been changing multiple spack/hdf5/openpmd-api versions to solve the issue I am reporting here, I just disregarded the dev branch option)
 1920  spack clean --all
 1921  spack install openpmd-api
# Successful installation (apparently) so I continued to the python installation of it
(...)
```

Then I used the following files (the `.cc` one I copied from https://openpmd-api.readthedocs.io/en/latest/usage/parallel.html#writing) - except with correct extensions (instead of `.txt`):

[opmd_build.sh.txt](https://github.com/openPMD/openPMD-api/files/6714914/opmd_build.sh.txt)
[opmd_run.sh.txt](https://github.com/openPMD/openPMD-api/files/6714915/opmd_run.sh.txt)
[test_opmd.cc.txt](https://github.com/openPMD/openPMD-api/files/6714916/test_opmd.cc.txt)
[CMakeLists.txt](https://github.com/openPMD/openPMD-api/files/6714919/CMakeLists.txt)

This led to the output file and errors below:

[output.txt](https://github.com/openPMD/openPMD-api/files/6714853/output.txt)

```
HDF5-DIAGHDF5-DIAG: Error detec: Error detected in ted in HDF5 (1.10.7) MPI-process 0:HDF5 (1.10.7) MPI-process 1:
  #000
  #000: H5T.c line: H5T.c line 2159 i 2159 in H5Tset_size(): size must be positive
n H5Tset_size(): size must be positive
    maj    major: Invalid arguments to routine
    mior: Invalid arguments to routine
    minor: nor: Bad value
Bad value
HDF5-DIAG:HDF5-DIAG: Error  Error detected in detected in HDF5HDF5 (1.10.7) MPI-pro (1.10.7) MPI-proccess 1:
  #000ess 0:
  #000: H5T.c: H5T.c line 2159 in  line 2159 in H5Tset_size(): size must be positive
    major:H5Tset_size(): size must be positive
    majo Invalid arguments to routine
    minor: Bad valuer: Invalid arguments to routine
    minor:
 Bad value
HDF5-DIAG: Error HDF5-DIAG: detected in Error detected HDF5 (1.10.7) MPI-procein HDF5 (1.10.7) MPI-pss 1:
  #000: H5T.c lrocess 0:
  ine 2159 in H5Tset_size()#000: H5T.c line 2159: size must be positive
    major: Invalid arguments to routine
     in H5Tset_size(): size must be positive
    mminor: Bad value
ajor: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.7) MPI-process 1:
  #000: H5T.c line 2159 in H5Tset_size(): size must be positive
    major: Invalid arguments to routine
    minor: HDF5-DIAG: Error detected in HDF5 (1.10.7) MPBad value
I-process 0:
  #000: H5T.c HDF5-DIAG: Error dline 2159 in H5Tset_size(): size must be positive
etected in HDF5 (1.10.7) M    major: Invalid arguments to routine
    minoPI-process 1:
r: Bad value
  #000: H5T.c line 2159 in H5Tset_size(): HDF5-DIAG: size must be positive
    major: Invalid arguments to routine
    miError detected nor: Bad value
in HDF5 (1.10.7) MPI-proceHDF5-DIAG: Errss 0:
  #000: H5T.c lor detected in HDF5 ine 2159 in H5Tset_size(): (1.10.7) MPI-processsize must be positive
    major: Invalid arguments to routine
    m 1:
  #000: H5T.c lininor: Bad value
e 2159 in H5Tset_size(): size must be positive
    major: Invalid arguments to routine
    minoHDF5-DIAG: Error: Bad value
r detected in HDF5 (1.10.7) MPI-process 0:
  #000: H5T.c line 2159 in H5Tset_size(): size must be positive
HDF5-DIAG: Error    major: Invalid arguments to routine
    mino detected in HDF5 (r: Bad value
1.10.7) MPI-process 1:
  #000: H5T.c line 2159 in H5Tset_size(): size must be positive
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.7) MPI-process 0:
  #000: H5T.c line 2159 in H5Tset_size(): size must be positive
    major: Invalid arguments to routine
    minor: Bad value
```

These errors *didn't occur* if I commented out everything in  `test_opmd.cc` between the "Ctreated an empty series ..." `cout` and `series.flush` (i.e. lines 45 to 72).
And *occurred* when I kept the `iterations` mesh construction (i.e. un-commenting lines 45 to 50).

These errors also don't seem to appear with the serial example.

**System environment**
 - operating system: Ubunto (`gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`)
 - machine: Local Windows 10
 - name and version of Python implementation: python installed via spack
 - output of `spack debug report`:

* **Spack:** 0.16.2-3140-ca1d1c427c
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original

**Additional context**
I will try to follow @ax3l 's suggestion of using environments with `spack` and will report back on it asap.
